apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodo-nodejs-k8s
  labels:
     app: nodo-nodejs-k8s
     type: front-end
spec:
  template:
     metadata:
       name: nodo-nodejs-k8s
       labels: 
         app: angular
         type: front-end
     spec:
         containers:
           - name: nodo-nodejs-k8s
             image: "yandihlg/jenkins-nodo-nodejs-bootcamp"
             imagePullPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      app: angular
      type: front-end